spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/messaging_db
    username: messaging_user
    password: messaging_password
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest